.TH GAMEMODED "1"
.SH NAME
gamemoded \- gamemode daemon for managing gamemode performance profiles
.SH SYNOPSIS
.B gamemoded
[\fI\,options\/\fR]
.SH DESCRIPTION
.B gamemoded
is a daemon/lib combo for Linux that allows games to request a set of optimisations be temporarily applied to the host OS.

The design has a clear-cut abstraction between the host daemon and library (gamemoded and libgamemode), and the client loaders (libgamemodeauto and gamemode_client.h) that allows for safe use without worrying about whether the daemon is installed or running. This design also means that while the host library currently relies on systemd for exchanging messages with the daemon, it's entirely possible to implement other internals that still work with the same clients.

GameMode was designed primarily as a stop-gap solution to problems with the Intel and AMD CPU powersave or ondemand governors, but is now able to launch custom user defined plugins, and is intended to be expanded further, as there are a wealth of automation tasks one might want to apply.
.SH OPTIONS
.TP
\fB\-d\fR
daemonize self after launch.
.TP
\fB\-l\fR
log to syslog.
.TP
\fB\-r\fR
request gamemode and pause.
.TP
\fB\-h\fR
print help.
.TP
\fB\-v\fR
print version.

.SH "SEE ALSO"
The
.B gamemode documentation
https://github.com/FeralInteractive/gamemode
.SH "BUGS"
Please report any bugs to https://github.com/FeralInteractive/gamemode/issues
.SH AUTHORS
.B gamemoded
is written by Feral Interactive. http://www.feralinteractive.com/
.LP
This man page is written by Jonathan Carter <jcc@debian.org>
